In [2]:
import pandas as pd

In [7]:
amazon = pd.read_csv('Datasets_limpios/amazon_limpio.csv')
disney = pd.read_csv('Datasets_limpios/disney_limpio.csv')
hulu = pd.read_csv('Datasets_limpios/hulu_limpio.csv')
netflix = pd.read_csv('Datasets_limpios/netflix_limpio.csv')

In [8]:
amazon['rating'] = amazon['rating'].str.lower()
disney['rating'] = disney['rating'].str.lower()
hulu['rating'] = hulu['rating'].str.lower()
netflix['rating'] = netflix['rating'].str.lower()

In [9]:
amazon['platform'] = 'amazon'
disney['platform'] = 'disney'
hulu['platform'] = 'hulu'
netflix['platform'] = 'netflix'

In [10]:
df = pd.concat([amazon,disney,hulu,netflix],axis=0)
df.sample(10)

,Unnamed: 0,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration_int,duration_type,duration,listed_in,description,score,platform
1761,1761,as1762,s1762,movie,majili,shiva nirvana,"naga chaitanya, samantha ruth, divyanshya",NaN,NaN,2019-01-01,13+,151.0,min,151 min,"drama, international, romance",a former cricket player nursing his wounds of ...,69,amazon
3027,3027,ns3028,s3028,movie,leslie jones: time machine,"david benioff, d.b. weiss",leslie jones,united states,2020-01-14,2020-01-01,tv-ma,66.0,min,66 min,stand-up comedy,from trying to seduce prince to battling sleep...,90,netflix
734,734,ds735,s735,movie,auntie edna,ted mathot,"brad bird, eli fucile, maeve andrews, nick bir...",united states,2019-11-12,2018-01-01,tv-g,7.0,min,7 min,"animation, comedy, family",has famous fashionista edna mode met her match...,54,disney
3000,3000,hs3001,s3001,tv show,up to speed,none,none,united states,2012-08-09,2012-01-01,tv-14,1.0,season,1 Season,"documentaries, lifestyle & culture","filmmaker richard linklater, best known for hi...",77,hulu
7808,7808,ns7809,s7809,tv show,qu√© pena tu serie,NaN,"ariel levy, andrea velasco, lucy cominetti, ig...",united states,2016-11-04,2015-01-01,tv-ma,1.0,season,1 Season,"international tv shows, romantic tv shows, spa...","javier is happily in love with sofia, so when ...",14,netflix
466,466,as467,s467,tv show,the ride that got away,NaN,"courtney hansen, troy ladd",NaN,NaN,2019-01-01,13+,1.0,season,1 Season,special interest,for every true car love there's the ride that ...,59,amazon
1660,1660,hs1661,s1661,movie,above the shadows,none,none,united states,2020-05-20,2019-01-01,111 min,NaN,NaN,NaN,"drama, science fiction","a supernatural tale starring olivia thirlby, a...",52,hulu
9060,9060,as9061,s9061,movie,the rookies,alan yuen,"talu wang, milla jovovich, sandrine pinna, dav...",NaN,NaN,2019-01-01,16+,113.0,min,113 min,action,extreme sport lover zhou feng got involved in ...,49,amazon
2719,2719,ns2720,s2720,movie,david batra: elefanten i rummet,"david batra, jon rudberg",david batra,sweden,2020-04-01,2020-01-01,tv-ma,77.0,min,77 min,stand-up comedy,swedish comedian david batra gets personal as ...,62,netflix
3830,3830,as3831,s3831,movie,leave it to beavers,pbs,brian unger,NaN,NaN,2014-01-01,7+,53.0,min,53 min,documentary,from pbs - the fascinating story of beavers in...,28,amazon

In [ ]:
amazon.to_csv('amazon_limpio.csv',index=False)
disney.to_csv('disney_limpio.csv',index=False)
hulu.to_csv('hulu_limpio.csv',index=False)
netflix.to_csv('netflix_limpio.csv',index=False)

In [11]:
df.to_csv('datos_completos.csv',index=False)

In [12]:
df.dtypes

Unnamed: 0         int64
id                object
show_id           object
type              object
title             object
director          object
cast              object
country           object
date_added        object
release_year      object
rating            object
duration_int     float64
duration_type     object
duration          object
listed_in         object
description       object
score              int64
platform          object
dtype: object